music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands, :albums, :tracks

end

music_app/app/models/album.rb
class Album < ApplicationRecord
  validates :title, :year, :band_id, presence: true
  validates :studio, inclusion: { in: [true, false], message:
    "Please select if the album was recorded in a studio" }

  belongs_to :band,
    foreign_key: :band_id,
    class_name: :Band

  has_many :tracks,
    foreign_key: :album_id,
    class_name: :Track,
    dependent: :destroy


end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :albums,
    foreign_key: :band_id,
    class_name: :Album,
    dependent: :destroy

  has_many :tracks,
    through: :albums,
    source: :tracks,
    dependent: :destroy
end

music_app/app/models/track.rb
class Track < ApplicationRecord
  validates :title, :album_id, :ord, :type, presence: true
  validates :type, inclusion: { in: %w(bonus regular), message: "Please select the type of track"}

  belongs_to :album,
    foreign_key: :album_id,
    class_name: :Album

end

music_app/app/models/user.rb
class User < ApplicationRecord
  validates :email, uniqueness: true, presence: true
  validates :password_digest, presence: { message: "Password can't be empty" }
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :session_token, presence: true, uniqueness: true

  attr_reader :password

  after_initialize :ensure_session_token

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    if user && user.is_password?(password)
      return user
    end
    nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end


end

music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    @albums = Album.all
    render :index
  end

  def show
    @album = Album.find_by(id: params[:id])
    @band = @album.band

    render :show
  end

  def new
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new(album_params)
    @band = @album.band

    if @album.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = [@album.errors.full_messages]
      render :new
    end

  end

  def destroy
    @album = Album.find_by(id: params[:id])
    @album.destroy
    @band = @album.band
    redirect_to band_url(@band)
  end

  def update
    @album = Album.find_by(id: params[:id])
    @band = @album.band

    if @album.update(album_params)
      flash.now[:success] = "You updated the Album info"
      redirect_to band_url(@band)
    else
      render :edit
    end

  end

  def edit
    @album = Album.find_by(id: params[:id])
    render :edit
  end

  private

  def album_params
    params.require(:album).permit(:title, :year, :studio, :band_id)
  end

end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    return nil unless session[:session_token].present?
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def log_out!
    current_user.reset_session_token!
    session[:session_token] = nil
  end


end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find_by(id: params[:id])

    render :show
  end

  def new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to bands_url
    else
      flash.now[:errors] = [@band.errors.full_messages]
      render :new
    end

  end

  def destroy
    @band = Band.find_by(id: params[:id])
    @band.destroy
    redirect_to bands_url
  end

  def update
    @band = Band.find_by(id: params[:id])

    if @band.update(band_params)
      flash.now[:success] = "You updated the band info"
      redirect_to band_url(@band)
    else
      render :edit
    end

  end

  def edit
    @band = Band.find_by(id: params[:id])
    render :edit
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end

end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    #should create a new session and log the user in
    @user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )

    if @user
      log_in_user!(@user)
      redirect_to bands_url
    else
      flash.now[:errors] = ["The email or the password are not correct"]
      render :new
    end
  end

  def destroy
    log_out!
    redirect_to new_session_url
  end

end

music_app/app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def index
    @tracks = Track.all
    render :index
  end

  def show
    @track = Track.find_by(id: params[:id])
    render :show
  end

  def new
    @track = Track.new
    render :new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to tracks_url
    else
      flash.now[:errors] = [@track.errors.full_messages]
      render :new
    end

  end

  def destroy
    @track = Track.find_by(id: params[:id])
    @track.destroy
    redirect_to tracks_url
  end

  def update
    @track = Track.find_by(id: params[:id])

    if @track.update(track_params)
      flash.now[:success] = "You updated the track info"
      redirect_to track_url(@track)
    else
      render :edit
    end

  end

  def edit
    @track = Track.find_by(id: params[:id])
    render :edit
  end

  private

  def track_params
    params.require(:track).permit(:title, :album_id, :ord, :lyrics, :track_type)
  end

end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in_user!(@user)
      # redirect_to ?
    else
      flash.now[:errors] = [@user.errors.full_messages]
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id]) 
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end

end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/app/views/albums/_form.html.erb
<% if type == :new %>
  <% action_url = albums_url %>
  <% submit_val = "Add a new Album" %>
<% elsif type == :edit %>
  <% action_url = album_url(album) %>
  <% submit_val = "Update Album" %>
<% end %>


<form action="<%= action_url %>" method="post">
  <% if type == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="title">Album Title</label>
  <input type="text" name="album[title]"
    value="<%= album.present? ? album.title : ""  %>"
    />
  <br><br>

  <label for="band_name">Band Name</label>
  <select id="band_name" name="album[band_id]">
    <% Band.all.each do |band| %>
      <option value="<%= band.id %>"
          <%= album.band_id ==  band.id ? "selected" : "" %> />
        <%= band.name %>
      </option>
    <% end %>
  </select>
  <br><br>

  <label>Studio
    <input type="radio" name="album[studio]" value="true"
      <%= album.studio ? "checked" : ""%> />
  </label>
  <label>Live
    <input type="radio" name="album[studio]" value="false"
      <%= album.studio ? "" : "checked" %> />
  </label>

  <br><br>
  <label for="year">Year</label>
  <input id="year" type="number" name="album[year]" value="<%= album.year  %>" />
  <br><br>
  <input type="submit" value="<%= submit_val %>"/>

</form>

  <% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
      <small style="color: red">
        <%= error %>
      </small>
    <% end %>
  <% end %>

music_app/app/views/albums/edit.html.erb
<%= render 'form', album: @album, type: :edit %>

<button>
  <a href="<%= band_url(@album.band)  %>" >Back to band</a>
</button>

music_app/app/views/albums/new.html.erb
<%= render 'form', album: @album, type: :new %>

<button>
  <a href="<%= bands_url  %>" >Back to all Bands</a>
</button>

music_app/app/views/albums/show.html.erb
<h3><%=  @album.title %> </h3>
<ul>
  <li> Year: <%=  @album.year %> </li>
  <li> Where: <%=   @album.studio ? "Studio" : "Live" %> </li>
  <li> Title: <%=  @album.title %> </li>
  <li> Band Name: <%=  @album.band.name %> </li>
</ul>

<button> <a href="<%= edit_album_url(@album) %>" >Edit Album</a></button>
<%= button_to 'Delete Album', album_url(@album), method: :delete %>

music_app/app/views/bands/edit.html.erb
<h3>Change Band Info</h3>

<form action="<%= band_url(@band) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label> Name:
    <input type="text" name="band[name]" value="<%= @band.name  %>">
  </lable>
  <br><br>
  <input type="submit" value="Update Band Info">
</form>

music_app/app/views/bands/index.html.erb
<h3>All Bands</h3>

<ul>
  <% @bands.each do |band| %>
    <li> <%= band.name %></li>
  <% end %>
</ul>

music_app/app/views/bands/new.html.erb
<h3>Add a New Band</h3>


<form action="<%= bands_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="text" name="band[name]">
  <br><br>
  <input type="submit" value="Add new Band">
</form>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <small style="color: red">
      <%= error %>
    </small>
  <% end %>
<% end %>

music_app/app/views/bands/show.html.erb
<h3>Band Name: <%=@band.name%></h3>

<small><% flash.now[:success] %></small>

<% if @band.albums.empty?  %>
  <small>Band dont have albums yet...</small>
<% else %>
  <ul>
    <% @band.albums.each do |album| %>
      <li><a href="<%= album_url(album) %>"> <%= album.title %> </a></li>
    <% end %>
  </ul>
<% end %>

<br>
<button> <a href="<%= edit_band_url %>" >Edit Band</a></button>
<%= button_to 'Delete Band', band_url(@band), method: :delete %>

<button> <a href="<%= new_album_url %>" >Add Album</a></button>

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <style>
      body {
          font-family: "Lucida Console", Monaco, monospace;
        }

      h1 {
        color: red;
        font-weight: bold;
      }

    small {
        display: inline-block;
      }




    </style>
  </head>

  <body>
    <section>
        <h1>Music App</h1>

        <p class="user-info">
          <% if current_user %>
            <small>
              Logged in as: <%= current_user.email %>
              <%= button_to 'Logout', session_url, method: :delete, class: 'logout' %>
            </small>
          <!-- <%# else %>
              <%#= link_to "Sign in", new_session_url %>
              <%#= link_to "Sign in", new_user_url %> -->
          <% end  %>
        </p>
        <%= yield %>

    </section>
  </body>
</html>

music_app/app/views/tracks/_form.html.erb
<% if type == :new %>
  <% action_url = tracks_url %>
  <% submit_val = "Add a new Track" %>
<% elsif type == :edit %>
  <% action_url = track_url(track) %>
  <% submit_val = "Update a Track" %>
<% end %>


<form action="<%= action_url %>" method="post">
  <% if type == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="title">Track Title</label>
  <input type="text" name="track[title]"
    value="<%= track.present? ? track.title : ""  %>"
    />
  <br><br>

  <label for="album_name">Album Name</label>
  <select id="album_name" name="track[album_id]">
    <% Album.all.each do |album| %>
      <option value="<%= album.id %>"
          <%= track.album_id ==  album.id ? "selected" : "" %> />
        <%= album.name %>
      </option>
    <% end %>
  </select>

  <br><br>

  <label>Track Type
    <input type="radio" name="track[track_type]" value="Regular"
      <%= track.track_type == regular ? "checked" : ""%> />
  </label>
  <label>Live
    <input type="radio" name="track[track_type]" value="Bonus"
      <%= track.track_type == regular ? "" : "checked" %> />
  </label>

  <br><br>

  <label>Lyrics
    <textarea name="track[lyrics]"> <%= track.lyrics %></textarea>
  </label>

  <br><br>

  <label for="order">Year</label>
  <input id="order" type="number" name="track[ord]" value="<%= track.ord  %>" />

  <br><br>

  <input type="submit" value="<%= submit_val %>"/>

</form>

  <% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
      <small style="color: red">
        <%= error %>
      </small>
    <% end %>
  <% end %>

music_app/app/views/tracks/edit.html.erb
<%= render 'form', album: @track, type: :edit %>

music_app/app/views/tracks/index.html.erb
<h3>All Tracks</h3>

<ul>
  <% @tracks.each do |track| %>
    <li> <%= track.title %></li>
  <% end %>
</ul>

music_app/app/views/tracks/new.html.erb
<%= render 'form', album: @track, type: :new %>

music_app/app/views/users/new.html.erb
<h3>Sign up!</h3>

<button>
  <%= link_to "Sign in!", new_session_url %>
</button>

<br><br>

<form action="<%= users_url %>" method="post">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>
    Email:
    <input type="text" name="user[email]" value="<%= @user.email  %>">
  </label>
  <br><br>

  <label>
    Password:
    <input type="password" name="user[password]">
  </label>
  <br><br>

  <button>Sign up</button>
</form>


  <% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
      <small style="color: red">
        <%= error %>
      </small>
    <% end %>
  <% end %>

music_app/app/views/users/show.html.erb
<h1>User <%= @user.email %> </h1>

<section>
  <ul>
    <li>Email: <%= @user.email %></li>
  </ul>
</section>